### ISSUE TITLE
응답속도가 빠르면서 성능이 괜찮은 LLM 모델을 찾는다

### ISSUE THREAD

**Issue by inspirit941** [AIFactory-CallPilot/Prompt-History-Archive#1]
우선순위: 응답속도 > 정확도. 비슷한 성능이라면 응답속도를 우선한다.
- colab 리소스 부족으로 모델이 제시간에 못 올라가는 timeout이 있을 수 있음.
- 모델이 쓰는 리소스 (cpu / memory) 양이 얼마인지, response time은 얼마나 걸리는지 체크 필요.

예시코드는 공유한 colab 참고.
- 예시로 쓸 텍스트 문장은 https://github.com/AIFactory-CallPilot/VoiceToText/issues/1 완료하면서 변환한 문장들을 추가할 예정.

![KakaoTalk_Photo_2023-06-16-20-59-04](https://github.com/AIFactory-CallPilot/Summarize/assets/26548454/9b53eb8b-b52e-4327-bbec-76adc1a52d2c)

AWS의 생성형 모델 가격은 얼마인지, LangChain으로 사용 가능한 인터페이스인지 / 아니면 AWS에서 따로 설정해서 써야 하는지 정도만 확인

&

최근 chatGPT api price / spec이 변경됨
- 토큰 개수 상한선이 4000개 이상인 api 추가됨 (더 비쌈)
- 더 비싼 gpt 모델 추가됨

https://readwrite.com/chatgpt-openai-api-updates-and-price-reductions-for-enhanced-performance/

**Comment by inspirit941** [comment]
**colab의 gpu 기준**으로 속도대비 성능이 가장 괜찮은 모델.

**Comment by juntaek118** [comment]
huggingface 기준으로 찾았을 때... 근데 colab에서의 timeout 에러 겪는중

EleutherAI/polyglot-ko-12.8b
EleutherAI/polyglot-ko-5.8b ..timeout error...?
beomi/KoAlpaca-Polyglot-5.8B 
beomi/KoAlpaca-Polyglot-12.8B
junelee/ko_vicuna_7b --> context length 2048

**Comment by inspirit941** [comment]
nvidia T4 (colab) 기준
동일한 input값 기준으로 응답시간 비교 (발표자료로 쓸 생각..)
-> 아마 결론은 chatGPT 쓰게 될 거 같음. 응답시간이 LLM 중 넘사벽 + GPU 머신 쓰면 월 270불 이상이 그냥 나감

그래서... 많이 찾을 필요는 없고, 유명한 모델 몇 개만 비교해도 충분할 듯?

**Comment by inspirit941** [comment]
huggingfaceHub에서 api timeout error 해결 못함... chatgpt 쓰는 쪽으로 결정
