### ISSUE TITLE
응답 품질을 개선하는 Prompt를 작성한다.

### ISSUE THREAD

**Issue by inspirit941** [AIFactory-CallPilot/Prompt-History-Archive#2]
단순 줄글로 대화내용 요약하는 것보다 더 좋은 방식이 있을 수 있음.
+ prompt에서 llm의 역할을 뭘로 정해주냐에 따라 성능차이가 있을 수 있음.

prompt관련 설명은 https://inspirit941.tistory.com/466 와 공유한 Note repository를 참고할 수 있다.

**Comment by juntaek118** [comment]
![Image](https://github.com/AIFactory-CallPilot/Summarize/assets/24493795/75cc5249-3eb0-444b-aeb0-6f82519561f2)

질문, 답변만 채우면 됨. 업무 메뉴얼 선택시 자동으로 입력되는 **유형**을 고려할 수 있으면 더 수월할 것 같음. 
    
- 접수번호 -> 자동
- 상담일시 -> 자동
- 센터구분 -> 자동
- 상담그룹 -> 자동
- **세부업무**
- 상담사  -> 자동
- 고객명
- 전화번호 -> 자동
- 핸드폰 -> 자동
- 인입번호 -> 자동
- **상담분야**
- 처리구분 -> 직접입력하면 좋을듯?
- 유형(대) -> 상담유형은 업무 매뉴얼 선택시 자동 세팅
- 유형(소) -> 상담유형은 업무 매뉴얼 선택시 자동 세팅
- 응답소접수번호
- 이관처리부서
- 이관처리구분
- 이관횟수
- **질문**
- **답변**
- 이관접수내용
- 이관처리내용
- 접수경로 -> 상담사

**Comment by juntaek118** [comment]
template = """
You are listening conversation of Seoul City sevice call center. This is Telephone Consultation with two persons. Topic of this conversation is %s
Write a summary of the conversation in one sentence of "질문" and one paragraph of "답변" format.

Conversation:
{text}

follwing the format below, Summary  in Korean
질문:
답변:
"""%category1

**Comment by juntaek118** [comment]
Question must be only one, and the answer too.

**Comment by juntaek118** [comment]
You are a counselor of Seoul City sevice call center. You will read conversation between customer and counselor. 
Write a summary of the conversation in triple backquote. Topic of this conversation is %s. 

Conversation:
```{text}```

Format must be one sentence of "질문" and one paragraph of "답변" .
Summary  in Korean. You must summarize "질문" in only one sentence. and summarize "답변" with detail. If there're specific price, number or name in counselor's answer, mention it.
질문:
답변:

**Comment by juntaek118** [comment]
호옥시나 STT 모델에서 화자 구분이 가능하다면 아주 좋을듯....

**Comment by juntaek118** [comment]
https://docs.google.com/presentation/d/1cVeY0Rc4FO_CXQZhjPQu78-HhVmV7KhWl2Gkh4UexIo/edit?usp=sharing
